version: "3.7"

services:
  bot:
    build: .
    command: /bin/sh -c "python main.py"
    ports:
      - "8000:80"
    env_file:
      - .env
    restart: always
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: on-failure
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data:
