"""changed url->file_id

Revision ID: 2b2e9884fd22
Revises: 7e9a2bfd27c6
Create Date: 2024-01-08 23:07:33.328739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b2e9884fd22'
down_revision: Union[str, None] = '7e9a2bfd27c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('file_id', sa.String(length=500), nullable=True))
    op.drop_column('products', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('products', 'file_id')
    # ### end Alembic commands ###
