"""added file type

Revision ID: 483cdfcced7c
Revises: 2b2e9884fd22
Create Date: 2024-01-08 23:45:41.516833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '483cdfcced7c'
down_revision: Union[str, None] = '2b2e9884fd22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('file_type', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'file_type')
    # ### end Alembic commands ###
