"""создаём ссылку для тарифа

Revision ID: 56f9881b2dbe
Revises: e5dd67fca135
Create Date: 2024-01-13 19:13:08.060410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56f9881b2dbe'
down_revision: Union[str, None] = 'e5dd67fca135'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tariffs', sa.Column('group_link', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tariffs', 'group_link')
    # ### end Alembic commands ###
