"""nullable=True, phone

Revision ID: 7e9a2bfd27c6
Revises: aa2df158cc61
Create Date: 2024-01-08 10:13:00.337331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e9a2bfd27c6'
down_revision: Union[str, None] = 'aa2df158cc61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=25),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=25),
               nullable=False)
    # ### end Alembic commands ###
