"""migrations 2

Revision ID: b8696327cc0d
Revises: 5c822259192f
Create Date: 2024-01-07 23:57:20.783382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8696327cc0d'
down_revision: Union[str, None] = '5c822259192f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_name_uzb', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('description_uzb', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('url', sa.String(length=500), nullable=True))
    op.add_column('tariffs', sa.Column('tariffs_name_uzb', sa.String(length=255), nullable=True))
    op.add_column('tariffs', sa.Column('description_uzb', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tariffs', 'description_uzb')
    op.drop_column('tariffs', 'tariffs_name_uzb')
    op.drop_column('products', 'url')
    op.drop_column('products', 'description_uzb')
    op.drop_column('products', 'product_name_uzb')
    # ### end Alembic commands ###
